1. What is a Python library? Why do we use Python libraries?

2. What is the difference between Numpy array and List?

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [5]:
import numpy as np
arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [6]:
arr.shape

(3, 4)

In [7]:
arr.size

12

In [8]:
arr.ndim

2

4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [9]:
arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [11]:
arr[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [12]:
arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [15]:
arr[2][3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [16]:
arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [20]:
arr[::,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

How can you generate a random 3x3 matrix with values between 0 and 1?

In [21]:
arr=np.random.rand(3,3)
arr

array([[0.22597883, 0.40544978, 0.95836358],
       [0.24113497, 0.93455987, 0.23829619],
       [0.56967532, 0.48301678, 0.54930554]])

8. Describe the difference between np.random.rand and np.random.randn?

In [24]:
arr=np.random.rand(2,3)
arr

array([[0.8580648 , 0.17488097, 0.48093216],
       [0.02398124, 0.7424887 , 0.75532105]])

In [26]:
arr1=np.random.randn(2,3)
arr1

array([[ 0.68939964, -2.6206296 ,  0.54916818],
       [-0.29245853, -0.75745457, -1.0589873 ]])

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [27]:
arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [28]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
arr.ndim

2

In [31]:
arr1=np.expand_dims(arr, axis=1)

In [32]:
arr1

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

10. How to transpose the following array in NumPy?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [33]:
arr=np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

In [34]:
arr1=np.transpose(arr)

In [35]:
arr1

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [36]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [37]:
#Index wise Multiplication
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr1=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [38]:
arr*arr1

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [39]:
np.multiply(arr,arr1)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [41]:
#Matix multiplication
arr1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
np.matmul(arr,arr1.reshape(4,3))

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [45]:
#Add both the matrix
np.add(arr,arr1)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [46]:
#Subtact matix B from a
np.subtract(arr,arr1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [47]:
#Divide Matix B by A
np.mod(arr1,arr)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

12. Which function in Numpy can be used to swap the byte order of an array?

13. What is the significance of the np.linalg.inv function?

15. What is broadcasting in Numpy?